name: irc test

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install SSH key
        run: |
          install -m 600 -D /dev/null > ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOY_SSH }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.DEPLOY_SSH }}@${{ secrets.SSH_HOST }} "cd &{{ secrets.WORK_DIR }} && git pull && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
